# Generated by Django 4.1.7 on 2023-04-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_resignart'),
    ]

    operations = [
        migrations.AddField(
            model_name='candels',
            name='product_image',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='candels',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resignart',
            name='product_image',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='resignart',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candels',
            name='product_dis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='candels',
            name='product_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resignart',
            name='product_dis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resignart',
            name='product_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
