# Generated by Django 4.1.7 on 2023-04-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_candels_product_image_candels_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candels',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resignart',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candels',
            name='product_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
