# Generated by Django 4.2 on 2023-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_candels_product_name_resignart_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candels',
            name='product_image',
            field=models.ImageField(default='', upload_to='genartful/media'),
        ),
        migrations.AlterField(
            model_name='resignart',
            name='product_image',
            field=models.ImageField(default='', upload_to='genartful/media'),
        ),
    ]
