# Generated by Django 4.2 on 2023-04-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_order_address_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
