# Generated by Django 4.2 on 2023-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_order_address_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.BigIntegerField(default=''),
        ),
    ]
