# Generated by Django 4.1.7 on 2023-04-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
